Repository keymanapp/keyman.com, pull requests merged in 2019-10, with the labels that each got.

#35 Update frontpage and 12/ page
  12/index.php
  _includes/includes/servervars.php
  desktop/features.php
  developer/features.php
  index.php
Labels: enhancement

#40 Address some points of issue #34
  about/index.php
  android/index.php
  cdn/dev/css/desktop-template.css
  cdn/dev/css/feature-template.css
  cdn/dev/img/android-sencoten.png
  cdn/dev/img/customers.png
  cdn/dev/js/kmlive.js
  desktop/features.php
  developer/download.php
  developer/features.php
  go/120/developer-help-mobile/index.php
  go/120/developer-help-packages/index.php
  index.php
  iphone-and-ipad/index.php
  linux/index.php
  testimonials/index.php
Labels: bug

#42 Refresh analytics code
  _includes/includes/analytics.php
  _includes/includes/head.php
  iphone-and-ipad/app/index.php
  iphone-and-ipad/app/systemkeyboard/index.php
  iphone-and-ipad/app/upgrade/index.php
Labels: enhancement

#27 [keyman.com] Staging for Keyman 12.0 release
  12/index.php
  12/predictive-text-editor.png
  12/predictive-text-ios.png
  12/predictive-text-khmer.png
  12/predictive-text-settings-android.png
  _includes/includes/servervars.php
  about/index.php
  android/index.php
  cdn/dev/css/desktop-template.css
  cdn/dev/css/feature-template.css
  cdn/dev/img/android-kmp.png
  cdn/dev/img/android-sencoten.png
  cdn/dev/img/customers.png
  cdn/dev/img/setup-click2.png
  cdn/dev/img/setup-click3.png
  cdn/dev/img/tab-support.png
  cdn/dev/js/kmlive.js
  desktop/features.php
  desktop/index.php
  developer/download.php
  developer/features.php
  developer/keymanweb/index.php
  developer/keymanweb/sample1.php
  downloads/_downloads.php
  downloads/archive/index.php
  downloads/index.php
  go/120/developer-help-mobile/index.php
  go/120/developer-help-packages/index.php
  index.php
  iphone-and-ipad/index.php
  linux/index.php
  testimonials/index.php
Labels: staging

#44 Updates Dinka link to latest version of keyboard.
  web.config
Labels: enhancement
