Repository keymanapp/keyman.com, pull requests merged in 2020-10, with the labels that each got.

#183 fix: linux - Clarify architecture
  linux/index.php
Labels: chore

#184 feat(ios): install page
  cdn/dev/keyboard-search/install.css
  cdn/dev/keyboard-search/search.css
  keyboards/install.php
Labels: feat

#182 chore/collect php error.log in ci
  .github/workflows/ci.yml
  cdn/dev/keyboard-search/install.css
  cdn/dev/keyboard-search/search.css
  keyboards/install.php
Labels: chore

#185 feat(android): Android install page
  keyboards/install.php
Labels: feat

#187 chore: update keyman windows installer filenames
  _includes/2020/KeymanDownloadVersions.php
  _includes/includes/ui/downloads.php
  desktop/download.php
  downloads/_downloads.php
  downloads/pre-release/index.php
Labels: chore

#188 chore: keyman windows installer filename (production)
  downloads/pre-release/index.php
Labels: chore, production

#189 chore: p10s17 master to staging
  linux/index.php
Labels: chore
