Repository keymanapp/keyman.com, pull requests merged in 2020-07, with the labels that each got.

#122 fix: phone menu visibility weird on responsive size
  cdn/dev/css/template.css
  cdn/dev/js/kmlive.js
Labels: fix

#121 chore: disable install pages for deprecated keyboards
  _includes/includes/ui/keyboard-details.php
Labels: chore

#120 feat: keyboard install pages
  _includes/2020/KeymanDownloadVersions.php
  _includes/2020/KeymanHosts.php
  _includes/2020/Validation.php
  _includes/2020/templates/AppStore.php
  _includes/2020/templates/Body.php
  _includes/2020/templates/Head.php
  _includes/2020/templates/Menu.php
  _includes/2020/templates/PlayStore.php
  _includes/async/keyboard-download.php
  _includes/includes/ui/keyboard-details.php
  cdn/dev/css/template.css
  cdn/dev/js/bowser.bundled.2.9.0.min.js
  cdn/dev/js/bowser.es5.2.9.0.min.js
  cdn/dev/js/kmlive.js
  cdn/dev/keyboard-search/install.css
  cdn/dev/keyboard-search/keyboard-details.js
  cdn/dev/keyboard-search/search.css
  cdn/dev/keyboard-search/search.js
  go/package/download.php
  go/web.config
  keyboards/download.php
  keyboards/install.php
  keyboards/keyboard.php
  keyboards/share.php
  web.config
Labels: feat

#124 chore: merge master into staging (P10S10 changes)
  mac/index.php
Labels: chore

#123 feat: define go/windows paths
  _includes/includes/ui/keyboard-details.php
  go/desktop/web.config
  go/windows/web.config
Labels: feat

#129 chore: use template host names so staging works
  10/index.php
  11/index.php
  _includes/2020/KeymanHosts.php
  _includes/2020/templates/Foot.php
  _includes/2020/templates/Menu.php
  _includes/includes/no-menu.php
  _includes/includes/ui/downloads.php
  _includes/includes/ui/keyboard-details.php
  _includes/includes/ui/legacy-keyboard-details.php
  _legacy/keyboards/index.php
  _legacy/keyboards/keyboard.json.php
  about/get-involved.php
  amharic/index.php
  android/index.php
  bookmarklet/index.php
  burmese/index.php
  cameroon/index.php
  composer.json
  contact/index.php
  developer/download.php
  developer/features.php
  developer/index.php
  developer/keymanweb/index.2.0.php
  developer/keymanweb/index.php
  developer/keymanweb/keyboards.php
  downloads/archive/index.php
  downloads/archive/legacy-embed.php
  engine/index.php
  eurolatin/index.php
  fonts/index.php
  free/index.php
  greek/index.php
  ipa/index.php
  iphone-and-ipad/index.php
  keyboards/index.php
  keyboards/keyboard.json.php
  linux/download.php
  linux/index.php
  mac/index.php
  sil-acquisition/index.php
  support/index.php
  tamil/anjal-paangu/index.php
  tamil/index.php
  tamil/isis/index.php
  tamil/new-typewriter/index.php
  tamil/suratha-bamuni/index.php
  tamil/visual-media-modular/index.php
  tamil/visual-media-typewriter/index.php
  tibetan/index.php
  tigrigna/eritrean.php
  tigrigna/index.php
  urdu/index.php
  web.config
Labels: chore

#130 feat: keyman protocol support in install page for Windows
  cdn/dev/keyboard-search/install.js
  cdn/dev/keyboard-search/keyboard-details.js
  keyboards/install.php
Labels: feat

#132 chore: move KeymanHosts.php to _common
  .github/workflows/ci.yml
  10/index.php
  11/index.php
  _common/KeymanHosts.php
  _includes/2020/KeymanDownloadVersions.php
  _includes/2020/Util.php
  _includes/2020/templates/Foot.php
  _includes/2020/templates/Menu.php
  _includes/includes/no-menu.php
  _includes/includes/servervars.php
  _includes/includes/ui/downloads.php
  _includes/includes/ui/keyboard-details.php
  _includes/includes/ui/legacy-keyboard-details.php
  _legacy/keyboards/index.php
  _legacy/keyboards/keyboard.json.php
  about/get-involved.php
  amharic/index.php
  android/index.php
  bookmarklet/index.php
  burmese/index.php
  cameroon/index.php
  contact/index.php
  developer/download.php
  developer/features.php
  developer/index.php
  developer/keymanweb/index.2.0.php
  developer/keymanweb/index.php
  developer/keymanweb/keyboards.php
  downloads/archive/index.php
  downloads/archive/legacy-embed.php
  engine/index.php
  eurolatin/index.php
  fonts/index.php
  free/index.php
  go/package/download.php
  greek/index.php
  ipa/index.php
  iphone-and-ipad/index.php
  keyboards/index.php
  keyboards/install.php
  keyboards/keyboard.json.php
  linux/download.php
  linux/index.php
  mac/index.php
  sil-acquisition/index.php
  support/index.php
  tamil/anjal-paangu/index.php
  tamil/index.php
  tamil/isis/index.php
  tamil/new-typewriter/index.php
  tamil/suratha-bamuni/index.php
  tamil/visual-media-modular/index.php
  tamil/visual-media-typewriter/index.php
  tibetan/index.php
  tigrigna/eritrean.php
  tigrigna/index.php
  urdu/index.php
Labels: chore

#133 feat: sentry integration
  .github/workflows/ci.yml
  _includes/includes/servervars.php
Labels: feat

#134 feat: traffic cone and lint test
  .github/workflows/ci.yml
  _includes/2020/templates/Menu.php
  _includes/includes/no-menu.php
  cdn/dev/img/logo2dev.png
Labels: feat

#136 fix: web.config had broken www redirect
  web.config
Labels: fix

#137 fix: reduce noise in lint and link check reporting
  .github/workflows/ci.yml
  composer.json
Labels: fix

#139 chore: Use new staging site for search
  cdn/dev/keyboard-search/search.js
Labels: chore

#140 feat: server-side support for iOS universal links
  .well-known/apple-app-site-association
Labels: enhancement

#138 fix: add error codes for go/package/download
  _common/JsonApiFailure.php
  _includes/2020/KeymanComSentry.php
  _includes/autoload.php
  _includes/includes/servervars.php
  go/package/download.php
Labels: fix

#142 feat: windows locale translation link
  go/windows/web.config
Labels: feat

#145 cherrypick: Add Android app association
  .gitignore
  .well-known/assetlinks.json
Labels: cherry-pick, enhancement
