Repository keymanapp/keyman.com, pull requests merged in 2020-05, with the labels that each got.

#97 feat: add reference to KAB
  engine/index.php
Labels: enhancement

#98 fix: ipa page is now responsive
  cdn/dev/css/template.css
  ipa/index.php
Labels: bug

#99 fix(linux): Add Linux to featured keyboards pages
  .editorconfig
  amharic/index.php
  cdn/dev/css/template.css
  tamil/anjal-paangu/index.php
  tamil/index.php
  tamil/isis/index.php
  tamil/new-typewriter/index.php
  tamil/suratha-bamuni/index.php
  tamil/visual-media-modular/index.php
  tamil/visual-media-typewriter/index.php
Labels: modification

#101 fix(linux): Fix download on Linux from featured keyboards pages
  cdn/dev/js/kmlive.js
Labels: bug

#100 fix(linux): Add Linux to featured keyboards page for Tamil
  tamil/index.php
Labels: enhancement
