Repository keymanapp/keyman.com, pull requests merged in 2020-01, with the labels that each got.

#70 Add if() to mac/ features
  linux/index.php
  mac/index.php
Labels: bug

#71 feat: online training announcement
  cdn/dev/css/template.css
  index.php
  training/index.php
Labels: enhancement

#73 fix(bookmarklet): url not escaped correctly
  bookmarklet/install-bookmarklet.js
Labels: bug

#74 Initial content for 13.0 beta announcement
  13/index.php
  13/ios-dark.png
  13/share-qr-code.png
  _includes/includes/servervars.php
  index.php
  web.config
Labels: enhancement, staging
