Repository keymanapp/keyman.com, pull requests merged in 2020-12, with the labels that each got.

#212 chore: disable beta pages until ready
  14/index.php
  _includes/2020/KeymanVersion.php
  index.php
Labels: chore

#213 chore: re-enable /14
  14/index.php
  index.php
Labels: chore

#214 fix: install link broken
  .gitignore
  keyboards/install.php
Labels: fix

#216 fix: monthly download stats on keyboard detail page
  _includes/includes/ui/keyboard-details.php
Labels: fix

#219 feat(linux): Rename onboard package
  downloads/pre-release/index.php
Labels: feat

#220 feat(linux): Rename onboard package
  14/index.php
  downloads/_downloads.php
  downloads/pre-release/index.php
  linux/download.php
  linux/index.php
Labels: feat, staging

#217 feat: add Sentry Javascript support
  _includes/2020/templates/Head.php
  cdn/dev/js/bundle.min.js.map
  cdn/dev/js/sentry.bundle.5.28.0.min.js
Labels: feat

#218 chore: rename Keyman Desktop to Keyman for Windows
  _includes/2020/templates/Foot.php
  _includes/2020/templates/Menu.php
  _includes/includes/desktop-features.php
  _includes/includes/ui/keyboard-details.php
  cdn/dev/css/template.css
  cdn/dev/js/kmlive.js
  desktop/download.php
  developer/features.php
  fonts/index.php
  go/windows/web.config
  index.php
  keyboards/h/amharic/index.php
  keyboards/h/burmese/index.php
  keyboards/h/cameroon/index.php
  keyboards/h/greek/index.php
  keyboards/h/sinhala/garp/index.php
  keyboards/h/sinhala/sipon/index.php
  keyboards/h/tamil/anjal-paangu/index.php
  keyboards/h/tamil/index.php
  keyboards/h/tamil/isis/index.php
  keyboards/h/tamil/new-typewriter/index.php
  keyboards/h/tamil/suratha-bamuni/index.php
  keyboards/h/tamil/visual-media-modular/index.php
  keyboards/h/tamil/visual-media-typewriter/index.php
  keyboards/h/tibetan/index.php
  keyboards/h/tigrigna/eritrean.php
  keyboards/h/tigrigna/index.php
  keyboards/h/urdu/index.php
  keyboards/install.php
  linux/index.php
  mac/index.php
  testimonials/index.php
  uninstall/index.php
  web.config
  windows/download.php
  windows/features.php
  windows/index.php
  windows/keepintouch-100.php
  windows/keepintouch-140.php
  windows/keyboards.php
Labels: chore

#222 chore: fixup dates
  14/index.php
  _includes/2020/KeymanVersion.php
  index.php
Labels: chore

#215 chore: beta 14 on production
  .gitignore
  14/index.php
  14/keyboard_search_khmer.png
  14/select_language.png
  _includes/includes/servervars.php
  index.php
  web.config
Labels: chore, production

#223 chore: add blog link
  14/index.php
Labels: chore

#224 chore: wording on beta
  14/index.php
Labels: chore

#226 feat(linux): Fix name of beta ppa
  14/index.php
  downloads/pre-release/index.php
Labels: chore

#227 feat: versioned download pages
  downloads/releases/_version_downloads.php
  downloads/releases/web.config
Labels: feat

#228 fix: polyfill for array_key_first
  downloads/releases/_version_downloads.php
Labels: fix
