Repository keymanapp/keyman.com, pull requests merged in 2020-09, with the labels that each got.

#160 chore: P10S14 merge master to staging
  about/index.php
  about/list.php
  cdn/dev/img/discourse-16.png
  cdn/dev/img/eberhard.png
  cdn/dev/img/email-16.png
  contact/index.php
Labels: chore

#161 modify: Add translate.keyman.com to get-involved
  about/get-involved.php
Labels: enhancement, staging

#162 feat: add model support to /go/package/download
  go/package/download.php
  go/web.config
Labels: feat

#164 fix: menu disappears with mouse move
  cdn/dev/css/template.css
  cdn/dev/js/kmlive.js
Labels: fix

#165 fix: console error on downlevel android
  cdn/dev/keyboard-search/search.js
Labels: fix

#166 fix: make obsolete banner visible at correct time
  _includes/includes/ui/keyboard-details.php
Labels: fix

#168 fix(common): staging for sentry
  _common/KeymanSentry.php
  go/package/download.php
Labels: fix

#169 feat: add landing pages to results
  cdn/dev/keyboard-search/dedicated-landing-pages.js
  cdn/dev/keyboard-search/search.css
  cdn/dev/keyboard-search/search.js
  keyboards/index.php
Labels: feat

#170 fix: sort of keyboard language names in keyboard details pages
  _includes/includes/ui/keyboard-details.php
Labels: fix

#171 fix: add links to keyboard details
  _includes/includes/ui/keyboard-details.php
  cdn/dev/keyboard-search/search.css
Labels: fix

#172 fix: keyboard install page for macOS
  cdn/dev/keyboard-search/install.css
  keyboards/install.php
Labels: fix

#173 fix: minor bugs in search
  cdn/dev/keyboard-search/search.js
Labels: fix

#178 fix: uasort instead of usort
  _includes/includes/ui/keyboard-details.php
Labels: fix

#179 fix: Change IPA link to bu_phonetic
  keyboards/h/ipa/index.php
Labels: cherry-pick, staging
