Repository keymanapp/keyman.com, pull requests merged in 2020-11, with the labels that each got.

#194 chore: P10S18 master staging
  keyboards/h/amharic/index.php
  keyboards/h/tigrigna/eritrean.php
  keyboards/h/tigrigna/index.php
Labels: chore

#196 fix: broken pagination after page 5
  cdn/dev/keyboard-search/search.js
Labels: fix

#198 fix: broken keyboard links
  _includes/includes/ui/keyboard-details.php
  cdn/dev/keyboard-search/search.css
Labels: fix

#197 chore: fixup internal keyboard links
  keyboards/h/greek/index.php
  keyboards/h/ipa/index.php
Labels: chore

#192 feat: markdown support
  _common/KeymanHosts.php
  _common/MarkdownHost.php
  _includes/includes/md/mdhost.php
  about/get-involved.md
  about/get-involved.php
  composer.json
  composer.lock
  web.config
Labels: enhancement, staging

#201 feat: Seed content for Keyman 14 beta announcement
  14/index.php
  14/keyboard_search_khmer.png
  14/select_language.png
  _common/KeymanHosts.php
  _includes/2020/KeymanVersion.php
  index.php
  web.config
Labels: staging

#203 fix: Chrome 85 breaks our clever download pattern
  cdn/dev/keyboard-search/install.js
  keyboards/install.php
Labels: fix

#204 fix: array.prototype.find polyfill
  cdn/dev/keyboard-search/search.js
Labels: fix

#205 chore: add startsWith polyfill
  cdn/dev/keyboard-search/search.js
Labels: chore
