Repository keymanapp/keyman.com, pull requests merged in 2020-08, with the labels that each got.

#141 feat: apple-app-site-association redux
  .well-known/apple-app-site-association
  .well-known/apple-app-site-association.json
  .well-known/web.config
Labels: feat

#146 fix: hide page statistics when few results
  cdn/dev/keyboard-search/search.js
Labels: fix

#147 fix: skip deprecated keyboards
  cdn/dev/keyboard-search/search.js
  downloads/archive/index.php
  keyboards/index.php
Labels: fix

#149 fix: search history and hints
  cdn/dev/keyboard-search/search.css
  cdn/dev/keyboard-search/search.js
  keyboards/index.php
Labels: fix

#148 fix: strip common words from search
  cdn/dev/keyboard-search/search.css
  cdn/dev/keyboard-search/search.js
  keyboards/index.php
Labels: fix

#150 fix: don't load search.js on detail page
  _includes/includes/ui/keyboard-details.php
  cdn/dev/keyboard-search/search.js
  keyboards/index.php
Labels: fix

#151 fix: non-unicode keyboards are obsolete too
  cdn/dev/keyboard-search/search.js
Labels: fix

#152 fix: filter keyboards for platform
  cdn/dev/keyboard-search/search.css
  cdn/dev/keyboard-search/search.js
  keyboards/index.php
Labels: fix

#144 chore: ci test change link for khmer
  .github/workflows/ci.yml
Labels: chore

#156 fix: iphone/ and ipad/ redirects were broken
  web.config
Labels: fix

#153 feat: rework download keyboard dialog style
  _includes/includes/ui/keyboard-details.php
  cdn/dev/keyboard-search/embed.css
  cdn/dev/keyboard-search/search.css
  cdn/dev/keyboard-search/search.js
  keyboards/index.php
Labels: feat

#157 chore: improve about links
  about/index.php
  about/list.php
  cdn/dev/img/discourse-16.png
  cdn/dev/img/email-16.png
  contact/index.php
Labels: chore

#135 feat: keyman protocol support in install page for Linux (keyman/#3271)
  .editorconfig
  cdn/dev/keyboard-search/install.css
  cdn/dev/keyboard-search/install.js
  keyboards/install.php
Labels: enhancement
