Repository keymanapp/keyman.com, pull requests merged in 2020-06, with the labels that each got.

#102 add more testimonials
  testimonials/index.php
Labels: modification

#105 Fix link to mac compatibility issues
  mac/index.php
Labels: bug

#104 feat: add tests and ci
  .github/workflows/ci.yml
  .gitignore
  _includes/async/keyboard-download.php
  _includes/includes/KeymanHosts.php
  _legacy/keyboards/keyboard.json.php
  composer.json
  composer.lock
  developer/keymanweb/index.php
  keyboards/download.php
  keyboards/keyboard.json.php
  package-lock.json
  package.json
  testimonials/index.php
  web.config
Labels: feat

#107 feat: highlight keyboard id in search
  cdn/dev/keyboard-search/search.js
Labels: feat

#108 feat: highlight more search terms
  cdn/dev/keyboard-search/search.js
Labels: feat

#109 feat: search pagination
  cdn/dev/keyboard-search/search.css
  cdn/dev/keyboard-search/search.js
  keyboards/index.php
Labels: feat

#110 refactor: use id code and tag more consistently for search
  cdn/dev/keyboard-search/search.js
Labels: fix

#111 feat: add bcp47 tag for embedded downloads
  _includes/includes/ui/keyboard-details.php
  cdn/dev/keyboard-search/search.js
  keyboards/keyboard.php
Labels: feat

#112 feat: show language codes in keyboard detail
  _includes/includes/ui/keyboard-details.php
  cdn/dev/keyboard-search/search.css
  cdn/dev/keyboard-search/search.js
  keyboards/index.php
Labels: feat

#113 fix: many pages in results needs ellipsis
  cdn/dev/keyboard-search/search.js
Labels: fix

#114 fix: obsolete keyboards in search
  _includes/includes/ui/keyboard-details.php
  cdn/dev/keyboard-search/search.css
  cdn/dev/keyboard-search/search.js
Labels: fix

#115 feat: popular keyboards
  cdn/dev/keyboard-search/search.js
Labels: feat

#106 fix: CI strategies for reporting on 500 errors
  .github/workflows/ci.yml
  _includes/includes/ui/keyboard-details.php
  cdn/dev/keyboard-search/search.css
  cdn/dev/keyboard-search/search.js
  keyboards/index.php
  keyboards/keyboard.php
  package.json
Labels: fix

#118 fix: typo in url
  cdn/dev/keyboard-search/search.js
  cdn/dev/legacy-keyboard-search/search.js
Labels: fix

#119 chore: Chance announcement to new keyboard search
  index.php
Labels: modification, staging
