Repository keymanapp/keyman.com, pull requests merged in 2020-02, with the labels that each got.

#75 Update Linux Beta info and link to community site
  13/index.php
Labels: enhancement

#76 Initial seed for staging 13.0 content
  13/index.php
  _includes/includes/servervars.php
  index.php
Labels: staging

#81 feat(android): Add 13.0 feature list
  android/index.php
Labels: enhancement

#79 feat(ios): adds 13.0 feature list, removes deprecated subpages
  iphone-and-ipad/app/index.php
  iphone-and-ipad/app/systemkeyboard/index.php
  iphone-and-ipad/app/upgrade/index.php
  iphone-and-ipad/app/web.config
  iphone-and-ipad/index.php
Labels: enhancement

#78 Minor edits for mac and linux
  13/index.php
  linux/index.php
Labels: staging

#82 Fix some prism styling and update go links for 13.0
  downloads/_downloads.php
  downloads/archive/index.php
  downloads/index.php
  downloads/pre-release/index.php
  go/100/developer-help-mobile/index.php
  go/100/developer-help-packages/index.php
  go/110/developer-help-mobile/index.php
  go/110/developer-help-packages/index.php
  go/120/developer-help-mobile/index.php
  go/120/developer-help-packages/index.php
  go/macos/10.0/download-keyboards/web.config
  go/macos/11.0/download-keyboards/web.config
  go/macos/12.0/download-keyboards/web.config
  go/macos/web.config
  go/web.config
Labels: enhancement

#77 Staging 13.0
  13/index.php
  _includes/includes/servervars.php
  android/index.php
  downloads/_downloads.php
  downloads/archive/index.php
  downloads/index.php
  downloads/pre-release/index.php
  go/100/developer-help-mobile/index.php
  go/100/developer-help-packages/index.php
  go/110/developer-help-mobile/index.php
  go/110/developer-help-packages/index.php
  go/120/developer-help-mobile/index.php
  go/120/developer-help-packages/index.php
  go/macos/10.0/download-keyboards/web.config
  go/macos/11.0/download-keyboards/web.config
  go/macos/12.0/download-keyboards/web.config
  go/macos/web.config
  go/web.config
  index.php
  iphone-and-ipad/app/index.php
  iphone-and-ipad/app/systemkeyboard/index.php
  iphone-and-ipad/app/upgrade/index.php
  iphone-and-ipad/app/web.config
  iphone-and-ipad/index.php
  linux/index.php
Labels: staging

#85 update linux installation instructions
  downloads/_downloads.php
  linux/download.php
  linux/index.php
Labels: bug

#86 fix: standalone download cleaner for desktop
  _includes/includes/ui/keyboard-details.php
  desktop/download.php
Labels: enhancement

#87 Update link for installing Keyman for macOS
  mac/index.php
Labels: enhancement

#88 fix: cameroon azerty web link
  cameroon/index.php
Labels: bug

#91 feat: Add android and ios platforms for keyboard search
  go/android/web.config
  go/ios/web.config
  keyboards/session.php
Labels: enhancement
