Repository keymanapp/keyman.com, pull requests merged in 2021-03, with the labels that each got.

#245 chore: release notes from B14S7
  14/index.php
Labels: chore

#246 chore: add redirect support to MarkdownHost
  _common/MarkdownHost.php
Labels: chore

#247 chore: tweak wording for beta
  14/index.php
Labels: chore

#248 Fix: keyboard landing pages when viewed on mobile
  cdn/dev/css/template.css
  keyboards/h/burmese/index.php
  keyboards/h/cameroon/index.php
  keyboards/h/greek/index.php
  keyboards/h/sinhala/index.php
  keyboards/h/tibetan/index.php
  keyboards/h/urdu/index.php
  web.config
Labels: chore

#249 chore: B14S8 master staging
  14/index.php
Labels: chore

#250 chore: Rename Windows download links
  downloads/_downloads.php
  downloads/archive/index.php
  downloads/releases/_version_downloads.php
  windows/download.php
Labels: chore, staging

#251 Update Android content for 14.0
  android/index.php
  cdn/dev/img/android-kmp.png
Labels: chore, staging

#257 chore: breaking changes and Keyman Engine
  14/index.php
  14/keyman-engine-changes.md
Labels: chore

#258 chore: tweak line breaks
  14/index.php
Labels: chore

#259 chore: breaking changes for staging 🍒
  14/index.php
  14/keyman-engine-changes.md
Labels: chore

#260 chore: smaller graphic
  14/index.php
  cdn/dev/img/screenshots/14/typewriter.jpg
Labels: chore

#261 chore: 14.0 launch changes (formerly staging to master)
  14/index.php
  14/webinar.md
  _legacy/web.config
Labels: chore

#262 chore(linux): Update download instructions
  linux/download.php
Labels: chore

#263 chore(linux): Add instructions for installing from pso
  linux/download.php
Labels: chore

#265 chore: Update site to 2000+ languages
  _includes/2020/templates/Menu.php
  _includes/includes/desktop-features.php
  index.php
  linux/index.php
  mac/index.php
  windows/index.php
Labels: chore

#266 chore: tweak language counts
  android/index.php
  engine/index.php
  index.php
  iphone-and-ipad/index.php
  linux/index.php
  mac/index.php
  windows/features.php
Labels: chore

#267 chore: Fix typo for Windows download link
  downloads/_downloads.php
Labels: bug

#273 feat: calendar links for webinars
  14/webinar.md
Labels: feat

#274 feat: zoom link for webinars
  14/webinar.md
Labels: feat

#275 fix: use cdn versions of stylesheets etc in keyboard search
  keyboards/index.php
Labels: fix

#280 chore: add slide and video links to webinars
  14/slides.svg
  14/video.png
  14/webinar.md
Labels: chore

#281 chore: add first webinar video
  14/webinar.md
Labels: chore

#282 fix: handle missing user agent
  _includes/includes/template.php
  keyboards/h/sinhala/index.php
Labels: fix

#283 fix: handle missing uninstall parameters
  uninstall/index.php
Labels: fix

#284 fix: support old versions of Firefox in install page
  cdn/dev/keyboard-search/install.js
Labels: fix

#288 chore: Fix *ZWNJ* typo
  developer/features.php
Labels: chore

#286 chore: more webinar videos
  14/webinar.md
Labels: chore
