Repository keymanapp/keyman.com, pull requests merged in 2021-01, with the labels that each got.

#229 chore(linux): Rename ppas
  14/index.php
  downloads/pre-release/index.php
Labels: chore

#230 chore: B14S3 master staging
  14/index.php
  downloads/releases/_version_downloads.php
  downloads/releases/web.config
  index.php
Labels: chore

#231 chore: use php 7.4 in actions
  .github/workflows/ci.yml
Labels: chore

#235 fix: bookmarklet list missing many keyboards
  bookmarklet/index.php
  bookmarklet/install-bookmarklet.js
Labels: fix

#233 fix: use full BCP 47 code for bookmarklet
  bookmarklet/index.php
  bookmarklet/install-bookmarklet.js
  cdn/dev/css/template.css
Labels: fix

#236 fix: sentry environment
  _includes/2020/templates/Head.php
Labels: fix

#234 feat: bookmarklet search
  bookmarklet/index.php
  bookmarklet/install-bookmarklet.js
  cdn/dev/css/template.css
Labels: feat

#237 fix: bookmarklet fixes for production 🍒
  bookmarklet/index.php
  bookmarklet/install-bookmarklet.js
  cdn/dev/css/template.css
Labels: cherry-pick, fix

#238 chore: B14S4 master staging
  14/index.php
  downloads/pre-release/index.php
Labels: chore

#239 fix: add examples for the search hints
  keyboards/index.php
Labels: fix

#240 fix: update search result when Back button pressed
  cdn/dev/keyboard-search/search.js
Labels: fix

#241 fix: hide package download link where appropriate
  _includes/includes/ui/keyboard-details.php
Labels: fix

#242 feat: popularity and alphabetical searches
  _includes/2020/templates/Head.php
  cdn/dev/css/template.css
  keyboards/index.php
Labels: feat

#243 chore: Add release notes from B14S4 sprint retrospective
  14/index.php
  linux/index.php
Labels: chore
