Repository keymanapp/keyman.com, pull requests merged in 2021-09, with the labels that each got.

#310 chore: Merge master branch from Sprint A15S14 into staging
  14/index.php
  14/webinar.md
  _common/KeymanHosts.php
  _includes/2020/templates/Head.php
  _includes/2020/templates/Menu.php
  _includes/includes/ui/keyboard-details.php
  cdn/dev/css/template.css
  cdn/dev/keyboard-search/install.css
  cdn/dev/keyboard-search/keyboard-details.js
  cdn/dev/keyboard-search/search.css
  cdn/dev/keyboard-search/search.js
  developer/download.php
  developer/features.php
  go/download/_download.php
  go/download/web.config
  go/package/download.php
  keyboards/index.php
  keyboards/install.php
  keyboards/session.php
  mac/download.php
  mac/index.php
  training/index.md
  training/index.php
  web.config
Labels: staging

#312 fix: Use css keyword `initial` instead of `unset` 🍒
  cdn/dev/keyboard-search/search.css
Labels: bug, cherry-pick

#311 fix: Use css keyword `initial` instead of `unset`
  cdn/dev/keyboard-search/search.css
Labels: bug

#313 chore: Sentry.io sponsor link
  about/index.php
  cdn/dev/img/sentry-wordmark-dark-400x119.svg
Labels: chore
