Repository keymanapp/keyman.com, pull requests merged in 2022-11, with the labels that each got.

#345 chore: move to 16.0 beta
  _common/MarkdownHost.php
  _includes/2020/KeymanVersion.php
  android/index.php
  developer/index.php
  iphone-and-ipad/index.php
  linux/index.php
  mac/index.php
  windows/index.php
Labels: chore

#346 change: uses centralized bookmarklet implementation 🔖
  bookmarklet/index.php
  bookmarklet/install-bookmarklet.js
  cdn/dev/css/template.css
Labels: change

#349 chore: basic security.txt
  .well-known/security.txt
Labels: chore

#350 fix(windows): disable text selection in embeded frames
  windows/keepintouch-100.php
  windows/keepintouch-140.php
Labels: fix

#353 chore: Fix broken link to font-helper
  fonts/index.php
Labels: bug

#354 chore: Fix broken link to download and install Keyman
  keyboards/install.php
Labels: chore
