Repository keymanapp/keyman.com, pull requests merged in 2023-10, with the labels that each got.

#391 chore: Merge master to staging for Sprint A17S22
  _includes/2020/templates/Foot.php
  _includes/includes/ui/contact-social.php
  about/index.php
  cdn/dev/css/template.css
  cdn/dev/img/facebook2.png
  cdn/dev/img/mastodon.svg
  cdn/dev/img/twitter2.png
  cdn/dev/img/youtube-16.png
  cdn/fonts/README.md
  cdn/fonts/social-logos.ttf
  contact/exception.php
  contact/index.php
Labels: staging

#389 chore: Update CI GHA to run with Docker 🦭
  .github/workflows/ci.yml
  Dockerfile
  _common/KeymanHosts.php
  build.sh
  composer.json
  composer.lock
Labels: staging

#393 fix: Add 301 permanent redirects 🦭
  .htaccess
  _legacy/.htaccess
  archive/.htaccess
  go/desktop/.htaccess
  go/developer/.htaccess
Labels: staging

#382 chore: remove deprecated field data from keyboard_info usage 🎺
  _includes/includes/ui/keyboard-details.php
Labels: staging, chore, epic-package-metadata

#394 Chore: merge staging from Sprint A17S23 to staging-apache 🦭
  _includes/includes/ui/keyboard-details.php
Labels: staging, chore, epic-linux-hosting

#395 chore: Use bootstrapping from shared-sites 🦭
  .gitignore
  _common/JsonApiFailure.php
  _common/KeymanHosts.php
  _common/KeymanSentry.php
  _common/MarkdownHost.php
  _common/README.md
  build.sh
  resources/builder.inc.sh
Labels: staging, chore, epic-linux-hosting

#396 chore: Remove web.config files 🦭
  .htaccess
  .well-known/web.config
  _legacy/web.config
  android/app/web.config
  archive/web.config
  downloads/releases/web.config
  go/android/web.config
  go/desktop/web.config
  go/developer/web.config
  go/download/web.config
  go/ios/web.config
  go/linux/web.config
  go/macos/web.config
  go/web.config
  go/windows/web.config
  iphone-and-ipad/app/web.config
  web.config
Labels: staging, epic-linux-hosting

#397 chore: Generate CDN in init-container.sh 🦭
  .gitattributes
  cdn/cdnrefresh.php
  resources/init-container.sh
Labels: staging

#398 chore: Add test page for /go links 🦭
  .gitignore
  .htaccess
  build.sh
  go/.htaccess
  go/download/.htaccess
  test/index.md
Labels: staging, epic-linux-hosting
