Repository keymanapp/keyman.com, pull requests merged in 2023-09, with the labels that each got.

#381 epic: Handle api.keyman.localhost and fix .htaccess 🦭
  .htaccess
  Dockerfile
  _common/KeymanHosts.php
  _common/KeymanSentry.php
  _includes/2020/templates/Head.php
  build.sh
  cdn/dev/keyboard-search/search.js
  cdn/dev/legacy-keyboard-search/search.js
  composer.json
  downloads/releases/.htaccess
  go/.htaccess
  go/android/.htaccess
  go/developer/.htaccess
  go/ios/.htaccess
  resources/builder.inc.sh
Labels: staging, epic-linux-hosting

#387 chore: Update site_suffix with KEYMAN_COM_PROXY_PORT 🦭
  _common/KeymanHosts.php
Labels: staging

#388 feat: add mastodon and youtube links
  _includes/2020/templates/Foot.php
  _includes/includes/ui/contact-social.php
  about/index.php
  cdn/dev/css/template.css
  cdn/dev/img/facebook2.png
  cdn/dev/img/mastodon.svg
  cdn/dev/img/twitter2.png
  cdn/dev/img/youtube-16.png
  cdn/fonts/README.md
  cdn/fonts/social-logos.ttf
  contact/exception.php
  contact/index.php
Labels: feat
