Repository keymanapp/keyman.com, pull requests merged in 2023-06, with the labels that each got.

#371 chore: remove Google Analytics
  _common/KeymanHosts.php
  _includes/2020/templates/Head.php
  _includes/includes/analytics.php
  _includes/includes/ui/legacy-keyboard-details.php
  _legacy/keyboards/download.php
  cdn/dev/js/kmlive.js
  go/package/download.php
  go/web.config
Labels: chore

#372 chore: merge master into staging (A17S14)
  _common/KeymanHosts.php
  _includes/2020/templates/Head.php
  _includes/includes/analytics.php
  _includes/includes/ui/legacy-keyboard-details.php
  _legacy/keyboards/download.php
  cdn/dev/js/kmlive.js
  go/package/download.php
  go/web.config
Labels: chore

#373 fix: Sentry:KEYMAN-COM-PR
  go/package/download.php
Labels: fix

#374 chore: merge master into staging (A17S15)
  go/package/download.php
Labels: staging
