Repository keymanapp/keyman.com, pull requests merged in 2024-10, with the labels that each got.

#472 feat: jobs/brisbane event first draft
  about/developers/index.md
  jobs/brisbane.md
Labels: feat

#477 fix: clean CDN cache on --debug
  resources/init-container.sh
Labels: fix

#480 fix: email styles in footer
  cdn/dev/css/template.css
Labels: fix

#481 fix: logo disappears from footer
  keyboards/keyboard.php
  search/index.php
Labels: fix

#482 chore: add date
  jobs/brisbane.md
Labels: chore

#483 chore: add short bio for ross
  about/developers/index.md
Labels: chore

#492 fix: exclude /donate from broken link checker
  .github/workflows/ci.yml
  build.sh
  composer.json
Labels: fix
