Repository keymanapp/keyman.com, pull requests merged in 2024-02, with the labels that each got.

#414 fix: go links for model/keyboards 🦭
  _test/go.md
  go/.htaccess
Labels: staging

#416 Update staging to use shared-sites v0.4
  build.sh
Labels: staging

#424 chore: Add info to .htaccess
  .htaccess
  _control/info.php
Labels: production

#427 chore: Merge master to staging for Sprint B17S1
  .htaccess
  _control/info.php
Labels: staging

#428 chore: move to 17.0 beta
  _includes/2020/KeymanVersion.php
Labels: chore

#431 chore: add about Mark Sinclair
  about/developers/index.md
Labels: chore
