Repository keymanapp/keyman.com, pull requests merged in 2024-12, with the labels that each got.

#514 chore: mid-sprint merge of master to staging for A18S16
  .github/workflows/add-to-keyman-project.yml
  _includes/2020/KeymanWebHost.php
  _includes/includes/ui/keyboard-details.php
  cdn/dev/keyboard-search/search.css
  developer/keymanweb/index.php
  go/.htaccess
  keyboards/h/amharic/index.php
  keyboards/h/burmese/index.php
  keyboards/h/cameroon/index.php
  keyboards/h/greek/index.php
  keyboards/h/ipa/index.php
  keyboards/h/sinhala/garp/index.php
  keyboards/h/sinhala/sipon/index.php
  keyboards/h/tamil/anjal-paangu/index.php
  keyboards/h/tamil/index.php
  keyboards/h/tamil/isis/index.php
  keyboards/h/tamil/new-typewriter/index.php
  keyboards/h/tamil/suratha-bamuni/index.php
  keyboards/h/tamil/visual-media-modular/index.php
  keyboards/h/tamil/visual-media-typewriter/index.php
  keyboards/h/tibetan/index.php
  keyboards/h/tigrigna/eritrean.php
  keyboards/h/tigrigna/index.php
  keyboards/h/urdu/index.php
Labels: staging

#517 feat: Configure `en_US` locale in Dockerfile 📡
  Dockerfile
  _includes/locale/README.md
  _includes/locale/en/LC_MESSAGES/.gitignore
  _includes/locale/en/LC_MESSAGES/.gitkeep
  resources/init-container.sh
Labels: staging

#518 fix: restore path in init-container.sh 📡
  resources/init-container.sh
Labels: staging

#519 feat: keyboard authoring service directory
  developer/authoring-services.md
  developer/index.php
Labels: feat

#520 feat: Add Locale.php class to set current locale 📡
  _includes/includes/template.php
  _includes/locale/Locale.php
  _includes/locale/README.md
  keyboards/index.php
  keyboards/session.php
Labels: staging

#522 fix: links to Keyman engine content
  iphone-and-ipad/index.php
Labels: fix
