Repository keymanapp/keyman.com, pull requests merged in 2024-11, with the labels that each got.

#491 fix missing closing tag on testimonial page
  testimonials/index.md
Labels: fix

#494 chore: only display errors in debug mode, otherwise log to stderr
  .gitignore
  .htaccess
  .user.ini
  applicationHost.xdt
  build.sh
Labels: chore

#489 fix: Specify HTML lang tag "en" 📓
  _includes/2020/templates/Head.php
Labels: fix

#490 fix: Add HTML lang tags for dedicated keyboard landing page examples 📓
  keyboards/h/amharic/index.php
  keyboards/h/ipa/index.php
  keyboards/h/tigrigna/eritrean.php
  keyboards/h/tigrigna/index.php
Labels: fix

#497 fix: Handle optional `language` tag in header
  _includes/2020/templates/Head.php
  _includes/includes/template.php
Labels: fix

#501 feat: show keyboard preview in keyboard details
  _includes/2020/KeymanWebHost.php
  _includes/includes/ui/keyboard-details.php
  cdn/dev/keyboard-search/search.css
  developer/keymanweb/index.php
Labels: feat

#475 fix: Modify stable url for keyboard download to kmp file
  go/.htaccess
Labels: fix

#509 feat: include 'Keyboard' in title for featured keyboards
  keyboards/h/amharic/index.php
  keyboards/h/burmese/index.php
  keyboards/h/cameroon/index.php
  keyboards/h/greek/index.php
  keyboards/h/ipa/index.php
  keyboards/h/sinhala/garp/index.php
  keyboards/h/sinhala/sipon/index.php
  keyboards/h/tamil/anjal-paangu/index.php
  keyboards/h/tamil/index.php
  keyboards/h/tamil/isis/index.php
  keyboards/h/tamil/new-typewriter/index.php
  keyboards/h/tamil/suratha-bamuni/index.php
  keyboards/h/tamil/visual-media-modular/index.php
  keyboards/h/tamil/visual-media-typewriter/index.php
  keyboards/h/tibetan/index.php
  keyboards/h/tigrigna/eritrean.php
  keyboards/h/tigrigna/index.php
  keyboards/h/urdu/index.php
Labels: feat

#511 chore: add new issues to Keyman project automatically
  .github/workflows/add-to-keyman-project.yml
Labels: chore

#513 fix: use property_exists instead of array_key_exists
  _includes/includes/ui/keyboard-details.php
Labels: fix
