Repository keymanapp/keyman.com, pull requests merged in 2025-02, with the labels that each got.

#537 Merge master to staging for beginning of Sprint B18S1
  _includes/includes/ui/keyboard-details.php
  about/developers/index.md
  cdn/dev/keyboard-search/search.css
  go/developer/.htaccess
  keyboards/session.php
Labels: staging

#538 fix: use KeymanWebHost::getKeymanWebUrlBase instead of $build global
  developer/keymanweb/index.php
Labels: fix

#539 chore: remove very old keymanweb 2.0 home
  developer/keymanweb/index.2.0.php
Labels: chore

#544 chore: update LDML page with current status as of Feb 2025
  .htaccess
  ldml/index.md
Labels: chore

#545 refactor: clean up KeymanHosts usage and make consistent
  12/index.php
  13/index.php
  14/index.php
  _control/info.php
  _ie_thunk/search.php
  _includes/2020/KeymanDownloadVersions.php
  _includes/2020/KeymanWebHost.php
  _includes/includes/servervars.php
  _includes/includes/ui/downloads.php
  _includes/includes/ui/keyboard-details.php
  _includes/includes/ui/legacy-keyboard-details.php
  _legacy/keyboards/download.php
  _legacy/keyboards/keyboard.json.php
  _legacy/keyboards/keyboard.php
  _legacy/keyboards/share.php
  android/index.php
  build.sh
  developer/keymanweb/keyboards.php
  developer/keymanweb/keymanweb-version.inc.php
  downloads/all-versions/index.php
  downloads/index.php
  downloads/pre-release/index.php
  downloads/releases/_version_downloads.php
  go/download/_download.php
  go/package/download.php
  iphone-and-ipad/index.php
  keyboards/install.php
  keyboards/keyboard.json.php
  keyboards/keyboard.php
  keyboards/share.php
Labels: refactor

#549 feat: add LT4All 2025 landing page for poster
  .htaccess
  ldml/lt4all.md
Labels: feat

#548 chore: improve sentry reporting
  _includes/2020/templates/Head.php
  _includes/includes/ui/keyboard-details.php
  build.sh
  cdn/dev/js/sentry.bundle.5.28.0.min.js
  cdn/dev/js/sentry.js
Labels: chore
