Repository keymanapp/keyman.com, pull requests merged in 2025-01, with the labels that each got.

#526 fix: avoid error when jsFilename is missing or mismatches package id
  _includes/includes/ui/keyboard-details.php
Labels: fix

#530 chore: Add Keyman is free and open source blurb
  _includes/2020/templates/Menu.php
  about/index.md
  cdn/dev/css/template.css
  free/index.md
  free/index.php
  index.php
Labels: chore

#521 feat: Localize keyboards index page 📡
  _includes/locale/Locale.php
  _includes/locale/README.md
  _includes/locale/en/LC_MESSAGES/keyboards-en.po
  _includes/locale/en/LC_MESSAGES/keyboards-es-ES.po
  _includes/locale/en/LC_MESSAGES/keyboards-fr-FR.po
  keyboards/index.php
Labels: staging

#531 chore: Merge master to staging for Sprint A18S20
  .htaccess
  _includes/2020/templates/Menu.php
  _includes/includes/ui/keyboard-details.php
  about/index.md
  build.sh
  cdn/dev/css/template.css
  developer/authoring-services.md
  developer/index.php
  free/index.md
  free/index.php
  index.php
  iphone-and-ipad/index.php
  jobs/index.md
Labels: staging

#536 feat(developer): support search for keyboards for TIKE project clone
  _includes/includes/ui/keyboard-details.php
  cdn/dev/keyboard-search/search.css
  go/developer/.htaccess
  keyboards/session.php
Labels: feat

#535 chore: add a section to `about/developers`
  about/developers/index.md
Labels: chore
